set nocompatible

filetype plugin indent on       " Load plugins according to detected filetype.
syntax on                                       " Enable syntax highlighting.

set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
set smartindent

" Stop indenting public/protected/private
set cino=g0

set backspace=indent,eol,start  " Make backspace work as you would expect.
set hidden                                              " Switch between buffers without having to save first.
set laststatus=2                                " Always show statusline.
set display=lastline                    " Show as much as possible of the last line.

set showcmd     " Show already typed keys when more are expected.

set incsearch   " Highlight while searching with / or ?.
set hlsearch    " Keep matches highlighted.

set ttyfast             " Faster redrawing.
set lazyredraw  " Only redraw when necessary.

set splitbelow  " Open new windows below the current window.
set splitright  " Open new windows right of the current window.

set cursorline          " Find the current line quickly.
set wrapscan            " Searches wrap around end-of-file.
set report=0            " Always report changed lines.

" Put all temporary files under the same directory.
set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo

" Tab expansion on commands
set wildmenu
set wildmode=full
"
" Show line numbers
set number relativenumber
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
	autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
set mouse=a     " Enable mouse controll

syntax on

" vim-plug plugin manager
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'chriskempson/base16-vim'
Plug 'majutsushi/tagbar'
Plug 'valloric/youcompleteme'
Plug 'tpope/vim-fugitive'

call plug#end()

"base-16 theme
colorscheme base16-default-dark
set termguicolors

let g:ycm_server_python_interpreter = '/bin/python2'

" Power line glyphs
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

let g:airline_theme='base16_default'

" sudo write
cmap w!! w !sudo tee > /dev/null %

" Buffer switching
nnoremap <C-l> :bn<CR>
nnoremap <C-h> :bp<CR>

autocmd BufRead *.sql set filetype=mysql
