set nocompatible

filetype plugin indent on       " Load plugins according to detected filetype.
syntax on                                       " Enable syntax highlighting.

set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
set smartindent

set backspace=indent,eol,start  " Make backspace work as you would expect.
set hidden                                              " Switch between buffers without having to save first.
set laststatus=2                                " Always show statusline.
set display=lastline                    " Show as much as possible of the last line.

set showcmd     " Show already typed keys when more are expected.

set incsearch   " Highlight while searching with / or ?.
set hlsearch    " Keep matches highlighted.

set ttyfast             " Faster redrawing.
set lazyredraw  " Only redraw when necessary.

set splitbelow  " Open new windows below the current window.
set splitright  " Open new windows right of the current window.

set cursorline          " Find the current line quickly.
set wrapscan            " Searches wrap around end-of-file.
set report=0            " Always report changed lines.
set synmaxcol=200       " Only highlight the first 200 columns.

" Put all temporary files under the same directory.
set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo

" Tab expansion on commands
set wildmenu
set wildmode=full

set number      " Show line numbers
set mouse=a     " Enable mouse controll

syntax on

" vim-plug plugin manager
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'chriskempson/base16-vim'
Plug 'scrooloose/syntastic'
Plug 'valloric/youcompleteme'

call plug#end()


" Power line glyphs
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" sudo write
cmap w!! w !sudo tee > /dev/null %

autocmd BufRead *.sql set filetype=mysql
