set nocompatible

set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
set smartindent

" Better wrapping
set breakindent
set showbreak=\\\\\\\
" Smarter j and k navigation
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'

" Stop indenting public/protected/private
set cino=g0
" Make backspace work as you would expect.
set backspace=indent,eol,start
" Switch between buffers without having to save first.
set hidden

" Show already typed keys when more are expected.
set showcmd
" Find the current line quickly.
set cursorline
" Searches wrap around end-of-file.
set wrapscan
set ignorecase
" Case aware completions
set infercase

" Put all temporary files under the same directory.
set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo

" Use system clipboard as default clipboard
set clipboard=unnamed

" Tab expansion on commands
set wildmenu
set wildmode=full

set mouse=a

" Sudo write
cmap w!! w !sudo tee > /dev/null %

" Buffer switching
nnoremap <C-l> :bn<CR>
nnoremap <C-h> :bp<CR>

" Show line numbers
set number relativenumber
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
	autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
" Enable mouse controll

autocmd BufRead *.sql set filetype=mysql


" vim-plug plugin manager
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'morhetz/gruvbox'
Plug 'valloric/youcompleteme'
Plug 'tpope/vim-fugitive'
Plug 'easymotion/vim-easymotion'
Plug 'JuliaEditorSupport/julia-vim'
Plug 'vim-latex/vim-latex'

call plug#end()

set background=dark
let g:gruvbox_italic=1
colorscheme gruvbox
set termguicolors

let g:ycm_server_python_interpreter = '/bin/python2'

" Power line glyphs
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

let g:airline_theme='gruvbox'

let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat="pdf"
let g:Tex_ViewRule_pdf='okular'
let g:Tex_MultipleCompileFormats="dvi,pdf"
